CREATE TABLE user(
	uid INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    phone_number VARCHAR(15) NOT NULL UNIQUE,
	gender VARCHAR(6) NOT NULL,	
    role varchar(10) DEFAULT 'END_USER' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE USER;

-- ALTER TABLE users
-- MODIFY COLUMN role varchar(10) DEFAULT 'END_USER'